### PR TITLE
scripts/cfbot.pl: use git grep facilities to extract Markdown sections

### PR DESCRIPTION
**Pull request by tzz**
This patch simplifies the code a lot by using `git grep --show-function` and eliminates duplicate matches.  I think it's very useful.

You need:

* `.gitattributes`: 
```
*.markdown diff=markdown
```

* `.gitconfig`:
```
[diff "markdown"]
      xfuncname = "^\\#+[ \\t]*(.+?)[ \\t]*\\#*$"
```

With those changes, `--show-function` will show a whole Markdown section, which we then collect into the list of matches.  We also don't parse Markdown by hand anymore.  The `summary` is now the whole section, though, so you may want to adjust that... let me know if you want a shorter summary or a different field with the full text or both.

### CODE REVIEW

**Comment by neilhwatson** [comment]
I spent some time looking at this and I have issues.

1. It's behind my weekend commit, which were significant.
2. Subs now require test plans.
3. The loading of %titles cannot account for an update in the CFE docs repo, or we have to search it every time reference_type

**Comment by tzz** [comment]
OK, rebased.  I cache the title loading.  I don't have the time to write the tests, unfortunately, but it works for me.

**Comment by neilhwatson** [comment]
Is this right? Look at 187-196. I've never seen that before

**Comment by tzz** [comment]
Assuming you mean the closure syntax, that's a way to scope variables privately to a function.

**Comment by tzz** [comment]
OK, fixed, I think.

**Pull request closed without merging**
